extends: 'eslint:recommended'
env:
  browser: true
  es6: true
globals:
  Phaser: readonly
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  no-console:
    - warn
    - allow:
      - log
  quotes:
    - error
    - single
  semi:
    - error
    - always
